# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\demo_fb.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(689, 431)
        Form.setStyleSheet("\n"
"/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    background-color: #232430;\n"
"    color: #000000;\n"
"    border-color: #000000;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: #232430;\n"
"    color: #c1c1c1;\n"
"    border-color: #000000;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"QPushButton\n"
"{\n"
"    background-color: #ff9c2b;\n"
"    color: #000000;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"    padding: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #ffaf5d;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #dd872f;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit\n"
"{\n"
"    background-color: #38394e;\n"
"    color: #c1c1c1;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: #4a4c68;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTableView-----*/\n"
"QTableView, \n"
"QHeaderView, \n"
"QTableView::item \n"
"{\n"
"    background-color: #232430;\n"
"    color: #c1c1c1;\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 691, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 195, 41);\n"
"color: rgb(61, 61, 61);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEditURL = QtWidgets.QLineEdit(Form)
        self.lineEditURL.setGeometry(QtCore.QRect(150, 136, 471, 31))
        self.lineEditURL.setStyleSheet("font: 12pt \"Calibri\";")
        self.lineEditURL.setObjectName("lineEditURL")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 121, 21))
        self.label_3.setStyleSheet("font: 12pt \"Calibri\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(150, 106, 461, 21))
        self.label_4.setStyleSheet("font: 12pt \"Calibri\";")
        self.label_4.setObjectName("label_4")
        self.pushButtonDownload = QtWidgets.QPushButton(Form)
        self.pushButtonDownload.setGeometry(QtCore.QRect(306, 200, 101, 31))
        self.pushButtonDownload.setStyleSheet("font: 12pt \"Calibri\";\n"
"")
        self.pushButtonDownload.setObjectName("pushButtonDownload")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(46, 300, 601, 21))
        self.progressBar.setStyleSheet("QProgressBar::chunk{\n"
"background-color: rgb(255, 92, 11);\n"
"margin-left:4px;\n"
"width:4px;\n"
"padding-right:4px;\n"
"\n"
"}\n"
"QProgressBar{\n"
"color:white;\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.labelWarning = QtWidgets.QLabel(Form)
        self.labelWarning.setGeometry(QtCore.QRect(6, 240, 671, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.labelWarning.setFont(font)
        self.labelWarning.setStyleSheet("font: 12pt \"Calibri\";")
        self.labelWarning.setText("")
        self.labelWarning.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWarning.setObjectName("labelWarning")
        self.labelProgressBar = QtWidgets.QLabel(Form)
        self.labelProgressBar.setGeometry(QtCore.QRect(10, 331, 671, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.labelProgressBar.setFont(font)
        self.labelProgressBar.setStyleSheet("font: 12pt \"Calibri\";")
        self.labelProgressBar.setText("")
        self.labelProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.labelProgressBar.setObjectName("labelProgressBar")
        self.pushButtonMinimize = QtWidgets.QPushButton(Form)
        self.pushButtonMinimize.setGeometry(QtCore.QRect(590, 0, 51, 23))
        self.pushButtonMinimize.setStyleSheet("background-color: rgb(95, 95, 95);\n"
"color:white;")
        self.pushButtonMinimize.setObjectName("pushButtonMinimize")
        self.pushButtonClose = QtWidgets.QPushButton(Form)
        self.pushButtonClose.setGeometry(QtCore.QRect(640, 0, 51, 23))
        self.pushButtonClose.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color:white;")
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(12, 50, 191, 22))
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(19, 20, 181, 21))
        self.label_5.setStyleSheet("font: 12pt \"Calibri\";")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Video Downloader"))
        self.label_3.setText(_translate("Form", "Enter video URL:"))
        self.label_4.setText(_translate("Form", "To download multiple videos insert links separated by comma"))
        self.pushButtonDownload.setText(_translate("Form", "Download"))
        self.pushButtonMinimize.setText(_translate("Form", "--"))
        self.pushButtonClose.setText(_translate("Form", "X"))
        self.label_5.setText(_translate("Form", "Slide to change themes"))
